# Generated by Django 3.0.4 on 2020-03-23 12:06

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200322_0922'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='blog_post_title_5e587a_gin'),
        ),
    ]
